version: 0.2

phases:
  install:
    commands:
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless
  # pre_build:
  #   commands:
  #     - npm install --silent --no-progress
  build:
    commands:
      - serverless package --stage prod --region ap-south-1  # Use "stg" or "prod" based on your environment
artifacts:
  files:
    - serverless.yml
